name: Build-Django-master

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      memcached:
        image: memcached:latest
        ports:
          - 11211:11211
    steps:
    - uses: actions/checkout@v2

    - name: Install libmemcached
      run: sudo apt-get install libmemcached-dev

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -q "https://github.com/django/django/archive/master.tar.gz"
        pip install .
        pip install -r requirements.txt

    - name: Test
      run: make test
